//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilestoneSvcReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConstructionMilestone", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class ConstructionMilestone : object
    {
        
        private MilestoneSvcReference.MilestoneAttachment[] AttachmentsField;
        
        private string ConstructionMilestoneCodeField;
        
        private string ConstructionMilestoneDescriptionField;
        
        private MilestoneSvcReference.Contractor ContractorField;
        
        private string ContractorNumberField;
        
        private int IdField;
        
        private string LoaContractNumberField;
        
        private string ManagingContractorCodeField;
        
        private int ManagingContractorIDField;
        
        private string OTCNumberField;
        
        private string OTCTypeCodeField;
        
        private string PONumberField;
        
        private System.Nullable<decimal> PercentageCompletionField;
        
        private System.Nullable<decimal> PercentageCompletionContractorField;
        
        private System.Nullable<decimal> PercentageCompletionEngineerField;
        
        private System.Nullable<decimal> PercentageCompletionQAField;
        
        private string PercentageReferenceNumberField;
        
        private MilestoneSvcReference.Punchlist[] PunchlistsField;
        
        private string ReferenceObjectField;
        
        private MilestoneSvcReference.ContractorRepresentative RepresentativeField;
        
        private MilestoneSvcReference.ContractorRepresentative[] RepresentativesField;
        
        private int SequenceField;
        
        private string TradeCodeField;
        
        private string TradeDescriptionField;
        
        private string VendorCodeField;
        
        private decimal WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.MilestoneAttachment[] Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                this.AttachmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConstructionMilestoneCode
        {
            get
            {
                return this.ConstructionMilestoneCodeField;
            }
            set
            {
                this.ConstructionMilestoneCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConstructionMilestoneDescription
        {
            get
            {
                return this.ConstructionMilestoneDescriptionField;
            }
            set
            {
                this.ConstructionMilestoneDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.Contractor Contractor
        {
            get
            {
                return this.ContractorField;
            }
            set
            {
                this.ContractorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractorNumber
        {
            get
            {
                return this.ContractorNumberField;
            }
            set
            {
                this.ContractorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoaContractNumber
        {
            get
            {
                return this.LoaContractNumberField;
            }
            set
            {
                this.LoaContractNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagingContractorCode
        {
            get
            {
                return this.ManagingContractorCodeField;
            }
            set
            {
                this.ManagingContractorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagingContractorID
        {
            get
            {
                return this.ManagingContractorIDField;
            }
            set
            {
                this.ManagingContractorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OTCNumber
        {
            get
            {
                return this.OTCNumberField;
            }
            set
            {
                this.OTCNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OTCTypeCode
        {
            get
            {
                return this.OTCTypeCodeField;
            }
            set
            {
                this.OTCTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PONumber
        {
            get
            {
                return this.PONumberField;
            }
            set
            {
                this.PONumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PercentageCompletion
        {
            get
            {
                return this.PercentageCompletionField;
            }
            set
            {
                this.PercentageCompletionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PercentageCompletionContractor
        {
            get
            {
                return this.PercentageCompletionContractorField;
            }
            set
            {
                this.PercentageCompletionContractorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PercentageCompletionEngineer
        {
            get
            {
                return this.PercentageCompletionEngineerField;
            }
            set
            {
                this.PercentageCompletionEngineerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PercentageCompletionQA
        {
            get
            {
                return this.PercentageCompletionQAField;
            }
            set
            {
                this.PercentageCompletionQAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PercentageReferenceNumber
        {
            get
            {
                return this.PercentageReferenceNumberField;
            }
            set
            {
                this.PercentageReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.Punchlist[] Punchlists
        {
            get
            {
                return this.PunchlistsField;
            }
            set
            {
                this.PunchlistsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceObject
        {
            get
            {
                return this.ReferenceObjectField;
            }
            set
            {
                this.ReferenceObjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.ContractorRepresentative Representative
        {
            get
            {
                return this.RepresentativeField;
            }
            set
            {
                this.RepresentativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.ContractorRepresentative[] Representatives
        {
            get
            {
                return this.RepresentativesField;
            }
            set
            {
                this.RepresentativesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence
        {
            get
            {
                return this.SequenceField;
            }
            set
            {
                this.SequenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeCode
        {
            get
            {
                return this.TradeCodeField;
            }
            set
            {
                this.TradeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeDescription
        {
            get
            {
                return this.TradeDescriptionField;
            }
            set
            {
                this.TradeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorCode
        {
            get
            {
                return this.VendorCodeField;
            }
            set
            {
                this.VendorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contractor", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class Contractor : object
    {
        
        private string CodeField;
        
        private string NameField;
        
        private MilestoneSvcReference.ContractorRepresentative[] RepresentativeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.ContractorRepresentative[] Representative
        {
            get
            {
                return this.RepresentativeField;
            }
            set
            {
                this.RepresentativeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractorRepresentative", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class ContractorRepresentative : object
    {
        
        private string ContactNumberField;
        
        private string ContractorCodeField;
        
        private string EmailField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber
        {
            get
            {
                return this.ContactNumberField;
            }
            set
            {
                this.ContactNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractorCode
        {
            get
            {
                return this.ContractorCodeField;
            }
            set
            {
                this.ContractorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MilestoneAttachment", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class MilestoneAttachment : object
    {
        
        private int ConstructionMilestoneIdField;
        
        private string FileNameField;
        
        private string FilePathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConstructionMilestoneId
        {
            get
            {
                return this.ConstructionMilestoneIdField;
            }
            set
            {
                this.ConstructionMilestoneIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath
        {
            get
            {
                return this.FilePathField;
            }
            set
            {
                this.FilePathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punchlist", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class Punchlist : object
    {
        
        private int AssignedToField;
        
        private MilestoneSvcReference.PunchlistCommentAttachment[] AttachmentFileNamesField;
        
        private MilestoneSvcReference.Comment CommentField;
        
        private MilestoneSvcReference.Comment[] CommentsField;
        
        private int ConstructionMilestoneIdField;
        
        private string ContractorNumberField;
        
        private MilestoneSvcReference.Coordinates CoordinatesField;
        
        private string CostImpactField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> DateCreatedField;
        
        private System.Nullable<System.DateTime> DateModifiedField;
        
        private MilestoneSvcReference.DeviceInfoModel DeviceInformationField;
        
        private System.Nullable<System.DateTime> DueDateField;
        
        private int ManagingContractorIDField;
        
        private string MessageField;
        
        private string MilestoneCodeField;
        
        private string NonCompliantToField;
        
        private string OTCNumberField;
        
        private string PunchListCategoryField;
        
        private string PunchListDescriptionField;
        
        private MilestoneSvcReference.PunchlistDescription PunchListDescriptionDetailsField;
        
        private string PunchListGroupField;
        
        private int PunchListIDField;
        
        private string PunchListLocationField;
        
        private string PunchListStatusField;
        
        private MilestoneSvcReference.PunchlistStatus PunchListStatusDetailField;
        
        private string PunchListSubCategoryField;
        
        private string ReferenceNumberField;
        
        private string ReferenceSheetField;
        
        private string ScheduleImpactField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssignedTo
        {
            get
            {
                return this.AssignedToField;
            }
            set
            {
                this.AssignedToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.PunchlistCommentAttachment[] AttachmentFileNames
        {
            get
            {
                return this.AttachmentFileNamesField;
            }
            set
            {
                this.AttachmentFileNamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.Comment Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.Comment[] Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConstructionMilestoneId
        {
            get
            {
                return this.ConstructionMilestoneIdField;
            }
            set
            {
                this.ConstructionMilestoneIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractorNumber
        {
            get
            {
                return this.ContractorNumberField;
            }
            set
            {
                this.ContractorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.Coordinates Coordinates
        {
            get
            {
                return this.CoordinatesField;
            }
            set
            {
                this.CoordinatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CostImpact
        {
            get
            {
                return this.CostImpactField;
            }
            set
            {
                this.CostImpactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated
        {
            get
            {
                return this.DateCreatedField;
            }
            set
            {
                this.DateCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this.DateModifiedField;
            }
            set
            {
                this.DateModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.DeviceInfoModel DeviceInformation
        {
            get
            {
                return this.DeviceInformationField;
            }
            set
            {
                this.DeviceInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagingContractorID
        {
            get
            {
                return this.ManagingContractorIDField;
            }
            set
            {
                this.ManagingContractorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MilestoneCode
        {
            get
            {
                return this.MilestoneCodeField;
            }
            set
            {
                this.MilestoneCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NonCompliantTo
        {
            get
            {
                return this.NonCompliantToField;
            }
            set
            {
                this.NonCompliantToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OTCNumber
        {
            get
            {
                return this.OTCNumberField;
            }
            set
            {
                this.OTCNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListCategory
        {
            get
            {
                return this.PunchListCategoryField;
            }
            set
            {
                this.PunchListCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListDescription
        {
            get
            {
                return this.PunchListDescriptionField;
            }
            set
            {
                this.PunchListDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.PunchlistDescription PunchListDescriptionDetails
        {
            get
            {
                return this.PunchListDescriptionDetailsField;
            }
            set
            {
                this.PunchListDescriptionDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListGroup
        {
            get
            {
                return this.PunchListGroupField;
            }
            set
            {
                this.PunchListGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PunchListID
        {
            get
            {
                return this.PunchListIDField;
            }
            set
            {
                this.PunchListIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListLocation
        {
            get
            {
                return this.PunchListLocationField;
            }
            set
            {
                this.PunchListLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListStatus
        {
            get
            {
                return this.PunchListStatusField;
            }
            set
            {
                this.PunchListStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.PunchlistStatus PunchListStatusDetail
        {
            get
            {
                return this.PunchListStatusDetailField;
            }
            set
            {
                this.PunchListStatusDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListSubCategory
        {
            get
            {
                return this.PunchListSubCategoryField;
            }
            set
            {
                this.PunchListSubCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceSheet
        {
            get
            {
                return this.ReferenceSheetField;
            }
            set
            {
                this.ReferenceSheetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScheduleImpact
        {
            get
            {
                return this.ScheduleImpactField;
            }
            set
            {
                this.ScheduleImpactField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class Comment : object
    {
        
        private string[] AttachmentFileNameField;
        
        private int CommentIdField;
        
        private MilestoneSvcReference.User CreatedByField;
        
        private string CreatedByUsernameField;
        
        private System.DateTime CreatedDateField;
        
        private System.DateTime DueDateField;
        
        private string[] ImageUrlField;
        
        private string MessageField;
        
        private int PunchlistIdField;
        
        private MilestoneSvcReference.PunchlistStatus PunchlistStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AttachmentFileName
        {
            get
            {
                return this.AttachmentFileNameField;
            }
            set
            {
                this.AttachmentFileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentId
        {
            get
            {
                return this.CommentIdField;
            }
            set
            {
                this.CommentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.User CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedByUsername
        {
            get
            {
                return this.CreatedByUsernameField;
            }
            set
            {
                this.CreatedByUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PunchlistId
        {
            get
            {
                return this.PunchlistIdField;
            }
            set
            {
                this.PunchlistIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.PunchlistStatus PunchlistStatus
        {
            get
            {
                return this.PunchlistStatusField;
            }
            set
            {
                this.PunchlistStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coordinates", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class Coordinates : object
    {
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceInfoModel", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class DeviceInfoModel : object
    {
        
        private MilestoneSvcReference.DeviceType DeviceTypeField;
        
        private string IdField;
        
        private string IdiomField;
        
        private string ManufacturerField;
        
        private string ModelField;
        
        private string NameField;
        
        private string PlatformField;
        
        private string VersionStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MilestoneSvcReference.DeviceType DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idiom
        {
            get
            {
                return this.IdiomField;
            }
            set
            {
                this.IdiomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer
        {
            get
            {
                return this.ManufacturerField;
            }
            set
            {
                this.ManufacturerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Platform
        {
            get
            {
                return this.PlatformField;
            }
            set
            {
                this.PlatformField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionString
        {
            get
            {
                return this.VersionStringField;
            }
            set
            {
                this.VersionStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistDescription", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistDescription : object
    {
        
        private string CodeField;
        
        private string GroupCodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupCode
        {
            get
            {
                return this.GroupCodeField;
            }
            set
            {
                this.GroupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistStatus", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistStatus : object
    {
        
        private string CodeField;
        
        private string CurrentStatusField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentStatus
        {
            get
            {
                return this.CurrentStatusField;
            }
            set
            {
                this.CurrentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistCommentAttachment", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistCommentAttachment : object
    {
        
        private int CommentIdField;
        
        private string FileNameField;
        
        private string FilePathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentId
        {
            get
            {
                return this.CommentIdField;
            }
            set
            {
                this.CommentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath
        {
            get
            {
                return this.FilePathField;
            }
            set
            {
                this.FilePathField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class User : object
    {
        
        private string EmailField;
        
        private string FullNameField;
        
        private string IdField;
        
        private System.Nullable<decimal> InspectionRadiusField;
        
        private bool IsActiveField;
        
        private string RoleCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InspectionRadius
        {
            get
            {
                return this.InspectionRadiusField;
            }
            set
            {
                this.InspectionRadiusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleCode
        {
            get
            {
                return this.RoleCodeField;
            }
            set
            {
                this.RoleCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceType", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public enum DeviceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Physical = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Virtual = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MilestoneSvcReference.IMilestoneService")]
    public interface IMilestoneService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilestoneService/GetMilestonesByUnit", ReplyAction="http://tempuri.org/IMilestoneService/GetMilestonesByUnitResponse")]
        System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone[]> GetMilestonesByUnitAsync(string username, string ReferenceObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilestoneService/GetMilestones", ReplyAction="http://tempuri.org/IMilestoneService/GetMilestonesResponse")]
        System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone[]> GetMilestonesAsync(string otcNumber, string contractorNumber, int ManagingContractorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilestoneService/GetMilestone", ReplyAction="http://tempuri.org/IMilestoneService/GetMilestoneResponse")]
        System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone> GetMilestoneAsync(string otcNumber, string contractorNumber, int ManagingContractorID, string milestoneCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilestoneService/GetMilestoneById", ReplyAction="http://tempuri.org/IMilestoneService/GetMilestoneByIdResponse")]
        System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone> GetMilestoneByIdAsync(string username, int constructionMilestoneId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilestoneService/UpdateMilestonePercentage", ReplyAction="http://tempuri.org/IMilestoneService/UpdateMilestonePercentageResponse")]
        System.Threading.Tasks.Task<bool> UpdateMilestonePercentageAsync(string userName, int ConstructionMilestoneId, string otcNumber, string contractorNumber, int managingContractorId, decimal newPercentage, string milestoneCode, MilestoneSvcReference.MilestoneAttachment[] attachments, System.Nullable<System.DateTime> dateVisited);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilestoneService/GetMilestoneByProject", ReplyAction="http://tempuri.org/IMilestoneService/GetMilestoneByProjectResponse")]
        System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone[]> GetMilestoneByProjectAsync(string username, string projectCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilestoneService/GetMilestonesByUnitByVendor", ReplyAction="http://tempuri.org/IMilestoneService/GetMilestonesByUnitByVendorResponse")]
        System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone[]> GetMilestonesByUnitByVendorAsync(string username, string ReferenceObject, string vendorCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilestoneService/GetMilestoneImages", ReplyAction="http://tempuri.org/IMilestoneService/GetMilestoneImagesResponse")]
        System.Threading.Tasks.Task<MilestoneSvcReference.MilestoneAttachment[]> GetMilestoneImagesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IMilestoneServiceChannel : MilestoneSvcReference.IMilestoneService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MilestoneServiceClient : System.ServiceModel.ClientBase<MilestoneSvcReference.IMilestoneService>, MilestoneSvcReference.IMilestoneService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MilestoneServiceClient() : 
                base(MilestoneServiceClient.GetDefaultBinding(), MilestoneServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMilestoneService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MilestoneServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MilestoneServiceClient.GetBindingForEndpoint(endpointConfiguration), MilestoneServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MilestoneServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MilestoneServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MilestoneServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MilestoneServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MilestoneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone[]> GetMilestonesByUnitAsync(string username, string ReferenceObject)
        {
            return base.Channel.GetMilestonesByUnitAsync(username, ReferenceObject);
        }
        
        public System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone[]> GetMilestonesAsync(string otcNumber, string contractorNumber, int ManagingContractorID)
        {
            return base.Channel.GetMilestonesAsync(otcNumber, contractorNumber, ManagingContractorID);
        }
        
        public System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone> GetMilestoneAsync(string otcNumber, string contractorNumber, int ManagingContractorID, string milestoneCode)
        {
            return base.Channel.GetMilestoneAsync(otcNumber, contractorNumber, ManagingContractorID, milestoneCode);
        }
        
        public System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone> GetMilestoneByIdAsync(string username, int constructionMilestoneId)
        {
            return base.Channel.GetMilestoneByIdAsync(username, constructionMilestoneId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateMilestonePercentageAsync(string userName, int ConstructionMilestoneId, string otcNumber, string contractorNumber, int managingContractorId, decimal newPercentage, string milestoneCode, MilestoneSvcReference.MilestoneAttachment[] attachments, System.Nullable<System.DateTime> dateVisited)
        {
            return base.Channel.UpdateMilestonePercentageAsync(userName, ConstructionMilestoneId, otcNumber, contractorNumber, managingContractorId, newPercentage, milestoneCode, attachments, dateVisited);
        }
        
        public System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone[]> GetMilestoneByProjectAsync(string username, string projectCode)
        {
            return base.Channel.GetMilestoneByProjectAsync(username, projectCode);
        }
        
        public System.Threading.Tasks.Task<MilestoneSvcReference.MilestoneAttachment[]> GetMilestoneImagesAsync()
        {
            return base.Channel.GetMilestoneImagesAsync();
        }
        
        public System.Threading.Tasks.Task<MilestoneSvcReference.ConstructionMilestone[]> GetMilestonesByUnitByVendorAsync(string username, string ReferenceObject, string vendorCode)
        {
            return base.Channel.GetMilestonesByUnitByVendorAsync(username, ReferenceObject, vendorCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMilestoneService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMilestoneService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9999/Milestone.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MilestoneServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMilestoneService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MilestoneServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMilestoneService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMilestoneService,
        }
    }
}
