// <auto-generated />
using System;
using Hcom.Web.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hcom.Web.Api.Migrations.FileUploadDB
{
    [DbContext(typeof(FileUploadDBContext))]
    [Migration("20220623012859_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hcom.Web.Api.ConstructionMilestoneBinaryImage", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cmiFileID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("cmiCreatedBy");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnName("cmiDateCreated");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnName("cmiDateModified");

                    b.Property<byte[]>("FileBinary")
                        .HasColumnName("cmiFileBinary");

                    b.Property<string>("FileName")
                        .HasColumnName("cmiFileName");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("cmiModifiedBy");

                    b.HasKey("FileID");

                    b.ToTable("ConstructionMilestoneBinaryImages");
                });

            modelBuilder.Entity("Hcom.Web.Api.PunchListBinaryImage", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cimFileID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("cimCreatedBy");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnName("cimDateCreated");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnName("cimDateModified");

                    b.Property<byte[]>("FileBinary")
                        .HasColumnName("cimFileBinary");

                    b.Property<string>("FileName")
                        .HasColumnName("cimFileName");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("cimModifiedBy");

                    b.HasKey("FileID");

                    b.ToTable("PunchListBinaryImages");
                });
#pragma warning restore 612, 618
        }
    }
}
