//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchlistSvcReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punchlist", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class Punchlist : object
    {
        
        private int AssignedToField;
        
        private PunchlistSvcReference.PunchlistCommentAttachment[] AttachmentFileNamesField;
        
        private PunchlistSvcReference.Comment CommentField;
        
        private PunchlistSvcReference.Comment[] CommentsField;
        
        private int ConstructionMilestoneIdField;
        
        private string ContractorNumberField;
        
        private PunchlistSvcReference.Coordinates CoordinatesField;
        
        private string CostImpactField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> DateCreatedField;
        
        private System.Nullable<System.DateTime> DateModifiedField;
        
        private PunchlistSvcReference.DeviceInfoModel DeviceInformationField;
        
        private System.Nullable<System.DateTime> DueDateField;
        
        private int ManagingContractorIDField;
        
        private string MessageField;
        
        private string MilestoneCodeField;
        
        private string NonCompliantToField;
        
        private string OTCNumberField;
        
        private string PunchListCategoryField;
        
        private string PunchListDescriptionField;
        
        private PunchlistSvcReference.PunchlistDescription PunchListDescriptionDetailsField;
        
        private string PunchListGroupField;
        
        private int PunchListIDField;
        
        private string PunchListLocationField;
        
        private string PunchListStatusField;
        
        private PunchlistSvcReference.PunchlistStatus PunchListStatusDetailField;
        
        private string PunchListSubCategoryField;
        
        private string ReferenceNumberField;
        
        private string ReferenceSheetField;
        
        private string ScheduleImpactField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssignedTo
        {
            get
            {
                return this.AssignedToField;
            }
            set
            {
                this.AssignedToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PunchlistSvcReference.PunchlistCommentAttachment[] AttachmentFileNames
        {
            get
            {
                return this.AttachmentFileNamesField;
            }
            set
            {
                this.AttachmentFileNamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PunchlistSvcReference.Comment Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PunchlistSvcReference.Comment[] Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConstructionMilestoneId
        {
            get
            {
                return this.ConstructionMilestoneIdField;
            }
            set
            {
                this.ConstructionMilestoneIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractorNumber
        {
            get
            {
                return this.ContractorNumberField;
            }
            set
            {
                this.ContractorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PunchlistSvcReference.Coordinates Coordinates
        {
            get
            {
                return this.CoordinatesField;
            }
            set
            {
                this.CoordinatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CostImpact
        {
            get
            {
                return this.CostImpactField;
            }
            set
            {
                this.CostImpactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated
        {
            get
            {
                return this.DateCreatedField;
            }
            set
            {
                this.DateCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this.DateModifiedField;
            }
            set
            {
                this.DateModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PunchlistSvcReference.DeviceInfoModel DeviceInformation
        {
            get
            {
                return this.DeviceInformationField;
            }
            set
            {
                this.DeviceInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagingContractorID
        {
            get
            {
                return this.ManagingContractorIDField;
            }
            set
            {
                this.ManagingContractorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MilestoneCode
        {
            get
            {
                return this.MilestoneCodeField;
            }
            set
            {
                this.MilestoneCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NonCompliantTo
        {
            get
            {
                return this.NonCompliantToField;
            }
            set
            {
                this.NonCompliantToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OTCNumber
        {
            get
            {
                return this.OTCNumberField;
            }
            set
            {
                this.OTCNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListCategory
        {
            get
            {
                return this.PunchListCategoryField;
            }
            set
            {
                this.PunchListCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListDescription
        {
            get
            {
                return this.PunchListDescriptionField;
            }
            set
            {
                this.PunchListDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PunchlistSvcReference.PunchlistDescription PunchListDescriptionDetails
        {
            get
            {
                return this.PunchListDescriptionDetailsField;
            }
            set
            {
                this.PunchListDescriptionDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListGroup
        {
            get
            {
                return this.PunchListGroupField;
            }
            set
            {
                this.PunchListGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PunchListID
        {
            get
            {
                return this.PunchListIDField;
            }
            set
            {
                this.PunchListIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListLocation
        {
            get
            {
                return this.PunchListLocationField;
            }
            set
            {
                this.PunchListLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListStatus
        {
            get
            {
                return this.PunchListStatusField;
            }
            set
            {
                this.PunchListStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PunchlistSvcReference.PunchlistStatus PunchListStatusDetail
        {
            get
            {
                return this.PunchListStatusDetailField;
            }
            set
            {
                this.PunchListStatusDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PunchListSubCategory
        {
            get
            {
                return this.PunchListSubCategoryField;
            }
            set
            {
                this.PunchListSubCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceSheet
        {
            get
            {
                return this.ReferenceSheetField;
            }
            set
            {
                this.ReferenceSheetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScheduleImpact
        {
            get
            {
                return this.ScheduleImpactField;
            }
            set
            {
                this.ScheduleImpactField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class Comment : object
    {
        
        private string[] AttachmentFileNameField;
        
        private int CommentIdField;
        
        private PunchlistSvcReference.User CreatedByField;
        
        private string CreatedByUsernameField;
        
        private System.DateTime CreatedDateField;
        
        private System.DateTime DueDateField;
        
        private string[] ImageUrlField;
        
        private string MessageField;
        
        private int PunchlistIdField;
        
        private PunchlistSvcReference.PunchlistStatus PunchlistStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AttachmentFileName
        {
            get
            {
                return this.AttachmentFileNameField;
            }
            set
            {
                this.AttachmentFileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentId
        {
            get
            {
                return this.CommentIdField;
            }
            set
            {
                this.CommentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PunchlistSvcReference.User CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedByUsername
        {
            get
            {
                return this.CreatedByUsernameField;
            }
            set
            {
                this.CreatedByUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PunchlistId
        {
            get
            {
                return this.PunchlistIdField;
            }
            set
            {
                this.PunchlistIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PunchlistSvcReference.PunchlistStatus PunchlistStatus
        {
            get
            {
                return this.PunchlistStatusField;
            }
            set
            {
                this.PunchlistStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coordinates", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class Coordinates : object
    {
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceInfoModel", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class DeviceInfoModel : object
    {
        
        private PunchlistSvcReference.DeviceType DeviceTypeField;
        
        private string IdField;
        
        private string IdiomField;
        
        private string ManufacturerField;
        
        private string ModelField;
        
        private string NameField;
        
        private string PlatformField;
        
        private string VersionStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PunchlistSvcReference.DeviceType DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idiom
        {
            get
            {
                return this.IdiomField;
            }
            set
            {
                this.IdiomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer
        {
            get
            {
                return this.ManufacturerField;
            }
            set
            {
                this.ManufacturerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Platform
        {
            get
            {
                return this.PlatformField;
            }
            set
            {
                this.PlatformField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionString
        {
            get
            {
                return this.VersionStringField;
            }
            set
            {
                this.VersionStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistDescription", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistDescription : object
    {
        
        private string CodeField;
        
        private string GroupCodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupCode
        {
            get
            {
                return this.GroupCodeField;
            }
            set
            {
                this.GroupCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistStatus", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistStatus : object
    {
        
        private string CodeField;
        
        private string CurrentStatusField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentStatus
        {
            get
            {
                return this.CurrentStatusField;
            }
            set
            {
                this.CurrentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistCommentAttachment", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistCommentAttachment : object
    {
        
        private int CommentIdField;
        
        private string FileNameField;
        
        private string FilePathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentId
        {
            get
            {
                return this.CommentIdField;
            }
            set
            {
                this.CommentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath
        {
            get
            {
                return this.FilePathField;
            }
            set
            {
                this.FilePathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class User : object
    {
        
        private string EmailField;
        
        private string FullNameField;
        
        private string IdField;
        
        private System.Nullable<decimal> InspectionRadiusField;
        
        private bool IsActiveField;
        
        private string RoleCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InspectionRadius
        {
            get
            {
                return this.InspectionRadiusField;
            }
            set
            {
                this.InspectionRadiusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleCode
        {
            get
            {
                return this.RoleCodeField;
            }
            set
            {
                this.RoleCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceType", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public enum DeviceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Physical = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Virtual = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistGroup", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistGroup : object
    {
        
        private string CategoryCodeField;
        
        private string CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryCode
        {
            get
            {
                return this.CategoryCodeField;
            }
            set
            {
                this.CategoryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistCategory", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistCategory : object
    {
        
        private string CodeField;
        
        private string NameField;
        
        private bool isComplianceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isCompliance
        {
            get
            {
                return this.isComplianceField;
            }
            set
            {
                this.isComplianceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistSubCategory", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistSubCategory : object
    {
        
        private string CodeField;
        
        private string NameField;
        
        private int OfficeDaysField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeDays
        {
            get
            {
                return this.OfficeDaysField;
            }
            set
            {
                this.OfficeDaysField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NonComplianceTo", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class NonComplianceTo : object
    {
        
        private string CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistLocation", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistLocation : object
    {
        
        private string CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CostImpact", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class CostImpact : object
    {
        
        private string CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleImpact", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class ScheduleImpact : object
    {
        
        private string CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistComment", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistComment : object
    {
        
        private string CreatedByField;
        
        private int IdField;
        
        private string MessageField;
        
        private int PunchlistIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PunchlistId
        {
            get
            {
                return this.PunchlistIdField;
            }
            set
            {
                this.PunchlistIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PunchlistAttachment", Namespace="http://schemas.datacontract.org/2004/07/CTI.HI.Business.Entities")]
    public partial class PunchlistAttachment : object
    {
        
        private string FileNameField;
        
        private string ImageUrlField;
        
        private int PunchlistIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PunchlistId
        {
            get
            {
                return this.PunchlistIdField;
            }
            set
            {
                this.PunchlistIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PunchlistSvcReference.IPunchlistService")]
    public interface IPunchlistService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlists", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistsResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.Punchlist[]> GetPunchlistsAsync(int ConstructionMilestoneId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistsByUnit", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistsByUnitResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.Punchlist[]> GetPunchlistsByUnitAsync(string username, string ReferenceObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlist", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.Punchlist> GetPunchlistAsync(int PunchlistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistDescriptions", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistDescriptionsResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistDescription[]> GetPunchlistDescriptionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistGroup", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistGroupResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistGroup[]> GetPunchlistGroupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistCategory", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistCategoryResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistCategory[]> GetPunchlistCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistSubCategory", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistSubCategoryResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistSubCategory[]> GetPunchlistSubCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetNonComplianceTo", ReplyAction="http://tempuri.org/IPunchlistService/GetNonComplianceToResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.NonComplianceTo[]> GetNonComplianceToAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistLocationAync", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistLocationAyncResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistLocation[]> GetPunchlistLocationAyncAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetCostImpact", ReplyAction="http://tempuri.org/IPunchlistService/GetCostImpactResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.CostImpact[]> GetCostImpactAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetScheduleImpact", ReplyAction="http://tempuri.org/IPunchlistService/GetScheduleImpactResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.ScheduleImpact[]> GetScheduleImpactAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistStatus", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistStatusResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistStatus[]> GetPunchlistStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistStatusByRole", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistStatusByRoleResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistStatus[]> GetPunchlistStatusByRoleAsync(string roleCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistbyProject", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistbyProjectResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.Punchlist[]> GetPunchlistbyProjectAsync(string username, string projectCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistComment", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistCommentResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistComment[]> GetPunchlistCommentAsync(int punchlistid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/SavePunchlist", ReplyAction="http://tempuri.org/IPunchlistService/SavePunchlistResponse")]
        System.Threading.Tasks.Task<int> SavePunchlistAsync(string username, PunchlistSvcReference.Punchlist model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetPunchlistsByUnitByVendor", ReplyAction="http://tempuri.org/IPunchlistService/GetPunchlistsByUnitByVendorResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.Punchlist[]> GetPunchlistsByUnitByVendorAsync(string username, string ReferenceObject, string vendorCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPunchlistService/GetMilestonePunchlistsImages", ReplyAction="http://tempuri.org/IPunchlistService/GetMilestonePunchlistsImagesResponse")]
        System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistAttachment[]> GetMilestonePunchlistsImagesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IPunchlistServiceChannel : PunchlistSvcReference.IPunchlistService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class PunchlistServiceClient : System.ServiceModel.ClientBase<PunchlistSvcReference.IPunchlistService>, PunchlistSvcReference.IPunchlistService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PunchlistServiceClient() : 
                base(PunchlistServiceClient.GetDefaultBinding(), PunchlistServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPunchlistService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PunchlistServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PunchlistServiceClient.GetBindingForEndpoint(endpointConfiguration), PunchlistServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PunchlistServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PunchlistServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PunchlistServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PunchlistServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PunchlistServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.Punchlist[]> GetPunchlistsAsync(int ConstructionMilestoneId)
        {
            return base.Channel.GetPunchlistsAsync(ConstructionMilestoneId);
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.Punchlist[]> GetPunchlistsByUnitAsync(string username, string ReferenceObject)
        {
            return base.Channel.GetPunchlistsByUnitAsync(username, ReferenceObject);
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.Punchlist> GetPunchlistAsync(int PunchlistId)
        {
            return base.Channel.GetPunchlistAsync(PunchlistId);
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistDescription[]> GetPunchlistDescriptionsAsync()
        {
            return base.Channel.GetPunchlistDescriptionsAsync();
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistGroup[]> GetPunchlistGroupAsync()
        {
            return base.Channel.GetPunchlistGroupAsync();
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistCategory[]> GetPunchlistCategoryAsync()
        {
            return base.Channel.GetPunchlistCategoryAsync();
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistSubCategory[]> GetPunchlistSubCategoryAsync()
        {
            return base.Channel.GetPunchlistSubCategoryAsync();
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.NonComplianceTo[]> GetNonComplianceToAsync()
        {
            return base.Channel.GetNonComplianceToAsync();
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistLocation[]> GetPunchlistLocationAyncAsync()
        {
            return base.Channel.GetPunchlistLocationAyncAsync();
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.CostImpact[]> GetCostImpactAsync()
        {
            return base.Channel.GetCostImpactAsync();
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.ScheduleImpact[]> GetScheduleImpactAsync()
        {
            return base.Channel.GetScheduleImpactAsync();
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistStatus[]> GetPunchlistStatusAsync()
        {
            return base.Channel.GetPunchlistStatusAsync();
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistStatus[]> GetPunchlistStatusByRoleAsync(string roleCode)
        {
            return base.Channel.GetPunchlistStatusByRoleAsync(roleCode);
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.Punchlist[]> GetPunchlistbyProjectAsync(string username, string projectCode)
        {
            return base.Channel.GetPunchlistbyProjectAsync(username, projectCode);
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistComment[]> GetPunchlistCommentAsync(int punchlistid)
        {
            return base.Channel.GetPunchlistCommentAsync(punchlistid);
        }
        
        public System.Threading.Tasks.Task<int> SavePunchlistAsync(string username, PunchlistSvcReference.Punchlist model)
        {
            return base.Channel.SavePunchlistAsync(username, model);
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.PunchlistAttachment[]> GetMilestonePunchlistsImagesAsync()
        {
            return base.Channel.GetMilestonePunchlistsImagesAsync();
        }
        
        public System.Threading.Tasks.Task<PunchlistSvcReference.Punchlist[]> GetPunchlistsByUnitByVendorAsync(string username, string ReferenceObject, string vendorCode)
        {
            return base.Channel.GetPunchlistsByUnitByVendorAsync(username, ReferenceObject, vendorCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPunchlistService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPunchlistService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9999/PunchlistService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PunchlistServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPunchlistService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PunchlistServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPunchlistService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPunchlistService,
        }
    }
}
